### PR TITLE
Disabled unused UI elements and fixed linkifier

### PR DESCRIPTION
**Pull request by marcominetti**
Cleanup for new frontend includes:
- hidden Emulation and Rendering tabs in Drawer
- disabled "Log XMLHttpRequest" in Console context menu
- hidden "Hide network messages" in Console filter bar
- disabled "Add Folder to Workspace" item in Sources Panel context menu
- hidden "Content scripts" tab in Sources Panel
- hidden DOM element selector button in toolbar
- fixed links to file not revealed because of 'file://' prefix missing

### CODE REVIEW

**Comment by marcominetti** [comment]
@3y3 I'm having problems with Console expression eval and consequently I'm not able to test preserve log.
I'll try to fix it tomorrow.
TODO: Saving profiler data is not implemented. Search in scripts source code is not implemented.

**Comment by marcominetti** [comment]
Commit #aa000e1c5713f6bb2abe1f96fd14195cd585f506 properly hide DOM selector button in toolbar through CSS instead of overriding "isWorkerFrontend" (that broke console).

**Comment by marcominetti** [comment]
@3y3 The latest commit fixes the debug port not read from frontend URI (querystring / params). The problem is that overriding WebInspector.Main.prototype._createConnection stuff (to correctly build the WebSocket URI thus including &port=DDDD) is not possibile with new frontend loading system: the function is called when the class is instanced and declared.

Solution:
- edit directly the front-end source code (I suppose this is the worst practice- requiring to re-patch on every update)
- include the port inside the ?ws=XXX querystring param

I've implemented the second one, now the debug port can be passed through URI in the following way:

http: //127.0.0.1:8081/debug?ws=127.0.0.1:8081**/5858**

Let me know if there is something else you prefer.

**Comment by marcominetti** [comment]
New commits:
- fixed add watchers not working (because of NewWatchExpression empty, now space)
- cleaned "/" redirection (now uses express redirect)
- removed FileSaver.js library to save profiles (now WebInspector.saveAs is available)
- fixed port query param (patched front-end code Main.js)
- commented useless css/dom/... stuff initialization (IMHO better performance)

TODO: search in content, preserve log (implement or hide), fix "Your node version (undefined)" bug, fix console autocompletion and remote object inspection exceptions if out of debug break, plugin system

**Comment by 3y3** [comment]
@marcominetti , please stop this. I can't review all this changes as one pr.

> cleaned "/" redirection (now uses express redirect)

Please describe this change as pr for `node-inspector/node-inspector`. It's ready to be merged.

The second step - divide this pr on two - `Fix saveAs` and `Hide useless elements`
Keep in mind that `hide elements` can be divided on some logical commits. (In current time you describe this logical parts only in messages). I also see changes in `front-end` folder - we can't do it.
After next frontend update we'll miss all this changes.

> fix console autocompletion and remote object inspection exceptions if out of debug break

This is work for me. Look at #450.

>  fix "Your node version (undefined)" bug

I work on this from time to time, but my current solution reimplements injecting system, I'd like to see something more simple if you want to work on this bug =)

**Comment by marcominetti** [comment]
Eheh ok... I'll revert, split and rebase to node-inspector... ;)

**Comment by 3y3** [comment]
`Eheh ok... I'll revert, split and rebase to node-inspector` I repeat this on each my new pr =)
This is a cost of `node-inspector` `--ff-only` git flow. I'm realy sorry for this strict rules =)

**Comment by marcominetti** [comment]
:D this is my very first pr/branch experience... Nice to learn!

**Comment by marcominetti** [comment]
Do you know if it is accepted to create a gruntfile to patch front-end folder on npm install?

**Comment by marcominetti** [comment]
I organized previous patches in separated branched ready for pr to node-inspector. I suppose we can close this PR.

**Pull request closed without merging**
